fixup! Don't set PATH in /etc/profile
When updating share/profile we also need to update its MD5 checksum in
share/profile.md5sums, otherwise the package fails to build on OBS with:

  sh debian/check-md5sum-etc profile
  Error: share/profile.md5sums is incomplete.
  Need to add 9d5ee34149287021622dd9e21c17ec26 with current version.
  debian/rules:17: recipe for target 'override_dh_auto_build' failed

https://phabricator.endlessm.com/T17924